name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22' # This will use the latest 1.x version of Go

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Cache ffi build
        uses: actions/cache@v4
        with:
          path: extern/filecoin-ffi
          key: ${{ runner.os }}-build-ffi

      - name: Build ffi deps
        run: make ffi-deps

      - name: Run Go tests
        run: go test -v ./...
